### ISSUE TITLE
Priority Filter

### ISSUE THREAD

**Issue by dannychuy** [compserv/hknweb#169]
Make events that pertain to each officer move to the top. Mandatory events are auto subscribed (GM, CM, HM) And Committee events (comm meeting, serv events for serv, etc.)

**Comment by bri25yu** [comment]
> Make events that pertain to each officer move to the top. 

Each cell in the events calendar is sorted by time, which imo makes more sense than sorting by priority.

> Mandatory events are auto subscribed (GM, CM, HM)

This would be good, but I'm honestly not sure how to do this, with the main problem being figuring out when to auto subscribe. Also the mandatory events are always shown in the candidate portal anyways. 

> And Committee events (comm meeting, serv events for serv, etc.)

Not sure how impactful this is overall, since there's on average 3 events per cell in the calendar. However, this is good feedback to kind of combine the calendar and all rsvps pages i.e. enable event type filtering and filter by rsvp on the calendar, maybe also with the ability to quickly rsvp to multiple events.

**Comment by bri25yu** [comment]
https://github.com/compserv/hknweb/commit/694f9c78ab629585e97f476803a5cceb3ba9fcb8
