### ISSUE TITLE
Prodev only slots on hkn-rails tutor calendar

### ISSUE THREAD

**Issue by bri25yu** [compserv/hknweb#485]
From Shivana
> would it be possible to have prodev oh slots marked as "prodev only" or something on the calendar? i think it's confusing people who don't scroll all the way down to see the prodev oh calendar

**Comment by bri25yu** [comment]
This wasn't the actual issue, but resolved by clearing certain Cory office hour slots. See https://gist.github.com/bri25yu/767f878086a911dc2956d302731d9de5. Credit to @ochan1

**Comment by ochan1** [comment]
Note that the above code only works because in this case, the ProDev people were in the slots
If there were other tutors, there would be some more code involved, but a good source of inspiration to work on this is: https://github.com/compserv/hkn-rails/blob/84b71703eaff8339bf69ad0f3ba998852283fcba/app/controllers/admin/tutor_controller.rb#L396-L398
